version: '3'

services:
  solid-nodejs-crud-database:
    image: ${DATABASE_CONTAINER_IMAGE}
    hostname: database
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
